---
- hosts: all
  tasks:
    - name: Set the hostname as defined in the inventory
      hostname: name={{ inventory_hostname }}
      tags:
      - configuration
      
    - name: Configure MOTD file
      template:
        src: motd.j2
        dest: /etc/motd
      tags:
      - configuration
      
    - name: "Install Common RPMS"
      yum: state=present name={{ item }}
      with_items:
      - bash-completion
      - tcpdump
      - vim
      - nmap-ncat
      - bind-utils
      - chrony
      - NetworkManager-glib
      - nm-connection-editor
      - libsemanage-python
      - policycoreutils-python
      tags:
      - packages
    
    - name: Ensure that the chronyd services is started
      service: name=chronyd state=started enabled=yes
      tags:
      - services
      
    - name: Ensure a default user is present  
      user: name=johnd comment="John Doe" uid=1040 group=users
      tags:
      - configuration
      
    - name: Make certain SELinux is set to enforcing  
      lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=enforcing
      tags:
      - configuration
  
